+ source ../common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Wed Aug  9 13:28:11 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL radvd
+ pkgs=radvd
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs radvd --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpam8he4l1
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpam8he4l1
++ ip route
++ grep 127.0.0.1
++ awk '{print $3}'
+ eth_name=
+ cp /etc/radvd.conf /etc/radvd.bak
+ echo 'interface 
{
        AdvSendAdvert on;
        MinRtrAdvInterval 3;
        MaxRtrAdvInterval 10;
        prefix 2001:db8:0:f101::1/64
        {
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr on;
        };

};'
+ echo 1
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Wed Aug  9 13:28:57 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Wed Aug  9 13:28:58 2023 - INFO  - Start testing...
+ test_execution radvd.service
+ service=radvd.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-08-09 13:28:58'
+ test_restart radvd.service
+ service=radvd.service
+ systemctl restart radvd.service
Job for radvd.service failed because the control process exited with error code.
See "systemctl status radvd.service" and "journalctl -xeu radvd.service" for details.
+ CHECK_RESULT 1 0 0 'radvd.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radvd.service restart failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radvd.service restart failed'
+ LOG_ERROR 'radvd.service restart failed'
+ message='radvd.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'radvd.service restart failed'
Wed Aug  9 13:28:59 2023 - ERROR - radvd.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Wed Aug  9 13:29:00 2023 - ERROR - ../common/common_lib.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status radvd.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'radvd.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radvd.service restart failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radvd.service restart failed'
+ LOG_ERROR 'radvd.service restart failed'
+ message='radvd.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'radvd.service restart failed'
Wed Aug  9 13:29:07 2023 - ERROR - radvd.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Wed Aug  9 13:29:08 2023 - ERROR - ../common/common_lib.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl stop radvd.service
+ CHECK_RESULT 0 0 0 'radvd.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='radvd.service stop failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status radvd.service
+ grep 'Active: inactive'
+ CHECK_RESULT 1 0 0 'radvd.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radvd.service stop failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radvd.service stop failed'
+ LOG_ERROR 'radvd.service stop failed'
+ message='radvd.service stop failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'radvd.service stop failed'
Wed Aug  9 13:29:15 2023 - ERROR - radvd.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Wed Aug  9 13:29:16 2023 - ERROR - ../common/common_lib.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start radvd.service
Job for radvd.service failed because the control process exited with error code.
See "systemctl status radvd.service" and "journalctl -xeu radvd.service" for details.
+ CHECK_RESULT 1 0 0 'radvd.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radvd.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radvd.service start failed'
+ LOG_ERROR 'radvd.service start failed'
+ message='radvd.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'radvd.service start failed'
Wed Aug  9 13:29:17 2023 - ERROR - radvd.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Wed Aug  9 13:29:18 2023 - ERROR - ../common/common_lib.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status radvd.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'radvd.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radvd.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radvd.service start failed'
+ LOG_ERROR 'radvd.service start failed'
+ message='radvd.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'radvd.service start failed'
Wed Aug  9 13:29:25 2023 - ERROR - radvd.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Wed Aug  9 13:29:26 2023 - ERROR - ../common/common_lib.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ test_enabled radvd.service
+ service=radvd.service
++ systemctl is-enabled radvd.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ grep 'Created symlink'
++ systemctl enable radvd.service
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/radvd.service
+ find /etc/systemd/system/multi-user.target.wants/radvd.service
/etc/systemd/system/multi-user.target.wants/radvd.service
+ CHECK_RESULT 0 0 0 'radvd.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='radvd.service enable failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable radvd.service
Removed /etc/systemd/system/multi-user.target.wants/radvd.service.
+ find /etc/systemd/system/multi-user.target.wants/radvd.service
find: ‘/etc/systemd/system/multi-user.target.wants/radvd.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'radvd.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='radvd.service disable failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2023-08-09 13:28:58' -u radvd.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
Aug 09 13:28:58 openeuler-riscv64 radvd[431]: /etc/radvd.conf:20 error: syntax error
Aug 09 13:28:58 openeuler-riscv64 radvd[431]: exiting, failed to read config file
Aug 09 13:28:58 openeuler-riscv64 systemd[1]: radvd.service: Control process exited, code=exited, status=1/FAILURE
Aug 09 13:28:58 openeuler-riscv64 systemd[1]: radvd.service: Failed with result 'exit-code'.
Aug 09 13:28:58 openeuler-riscv64 systemd[1]: Failed to start Router advertisement daemon for IPv6.
Aug 09 13:29:16 openeuler-riscv64 radvd[447]: /etc/radvd.conf:20 error: syntax error
Aug 09 13:29:16 openeuler-riscv64 radvd[447]: exiting, failed to read config file
Aug 09 13:29:16 openeuler-riscv64 systemd[1]: radvd.service: Control process exited, code=exited, status=1/FAILURE
Aug 09 13:29:16 openeuler-riscv64 systemd[1]: radvd.service: Failed with result 'exit-code'.
Aug 09 13:29:16 openeuler-riscv64 systemd[1]: Failed to start Router advertisement daemon for IPv6.
+ CHECK_RESULT 0 0 1 'There is an error message for the log of radvd.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of radvd.service'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of radvd.service'
+ LOG_ERROR 'There is an error message for the log of radvd.service'
+ message='There is an error message for the log of radvd.service'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of radvd.service'
Wed Aug  9 13:29:33 2023 - ERROR - There is an error message for the log of radvd.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Wed Aug  9 13:29:34 2023 - ERROR - ../common/common_lib.sh line 28
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start radvd.service
Job for radvd.service failed because the control process exited with error code.
See "systemctl status radvd.service" and "journalctl -xeu radvd.service" for details.
+ sed -i 's\ExecStart=/usr/sbin/radvd\ExecStart=/usr/sbin/radvd -m\g' /usr/lib/systemd/system/radvd.service
+ systemctl daemon-reload
+ systemctl reload radvd.service
radvd.service is not active, cannot reload.
+ CHECK_RESULT 1 0 0 'radvd.service reload failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radvd.service reload failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radvd.service reload failed'
+ LOG_ERROR 'radvd.service reload failed'
+ message='radvd.service reload failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'radvd.service reload failed'
Wed Aug  9 13:29:38 2023 - ERROR - radvd.service reload failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_radvd.sh line 51'
+ message='oe_test_service_radvd.sh line 51'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_radvd.sh line 51'
Wed Aug  9 13:29:39 2023 - ERROR - oe_test_service_radvd.sh line 51
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl status radvd.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'radvd.service reload causes the service status to change'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='radvd.service reload causes the service status to change'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'radvd.service reload causes the service status to change'
+ LOG_ERROR 'radvd.service reload causes the service status to change'
+ message='radvd.service reload causes the service status to change'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'radvd.service reload causes the service status to change'
Wed Aug  9 13:29:40 2023 - ERROR - radvd.service reload causes the service status to change
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_radvd.sh line 53'
+ message='oe_test_service_radvd.sh line 53'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_radvd.sh line 53'
Wed Aug  9 13:29:41 2023 - ERROR - oe_test_service_radvd.sh line 53
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Wed Aug  9 13:29:42 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Aug  9 13:29:43 2023 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Wed Aug  9 13:29:44 2023 - INFO  - start environment cleanup.
+ sed -i 's\ExecStart=/usr/sbin/radvd -m\ExecStart=/usr/sbin/radvd\g' /usr/lib/systemd/system/radvd.service
+ systemctl daemon-reload
+ systemctl reload radvd.service
radvd.service is not active, cannot reload.
+ systemctl stop radvd.service
+ mv -f /etc/radvd.bak /etc/radvd.conf
+ echo 0
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpam8he4l1 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpam8he4l1
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Wed Aug  9 13:30:03 2023 - INFO  - Finish environment cleanup!
