+ source ../common/net_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Tue Aug  8 19:08:14 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL 'net-tools systemd-resolved'
+ pkgs='net-tools systemd-resolved'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'net-tools systemd-resolved' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp95x9ob7v
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp95x9ob7v
+ cp -r /etc/NetworkManager/NetworkManager.conf /etc/NetworkManager/NetworkManager.conf_bak
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Tue Aug  8 19:10:01 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Aug  8 19:10:03 2023 - INFO  - Start to run test.
+ SLEEP_WAIT 6
+ wait_time=6
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 6 --cmd '' --mode 1
+ systemctl --now enable systemd-resolved
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nmcli_systemd_resolved.sh line 32'
+ message='oe_test_nmcli_systemd_resolved.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nmcli_systemd_resolved.sh line 32'
Tue Aug  8 19:10:13 2023 - ERROR - oe_test_nmcli_systemd_resolved.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ sed -i '/main]/adns=systemd-resolved' /etc/NetworkManager/NetworkManager.conf
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl reload NetworkManager
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nmcli_systemd_resolved.sh line 36'
+ message='oe_test_nmcli_systemd_resolved.sh line 36'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nmcli_systemd_resolved.sh line 36'
Tue Aug  8 19:10:15 2023 - ERROR - oe_test_nmcli_systemd_resolved.sh line 36
+ '[' 0 -eq 1 ']'
+ return 0
+ netstat -tulpn
+ grep 127.0.0.53:53
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nmcli_systemd_resolved.sh line 38'
+ message='oe_test_nmcli_systemd_resolved.sh line 38'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nmcli_systemd_resolved.sh line 38'
Tue Aug  8 19:10:18 2023 - ERROR - oe_test_nmcli_systemd_resolved.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Aug  8 19:10:19 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Aug  8 19:10:21 2023 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Aug  8 19:10:22 2023 - INFO  - Start to restore the test environment.
+ mv -f /etc/NetworkManager/NetworkManager.conf_bak /etc/NetworkManager/NetworkManager.conf
+ systemctl reload NetworkManager
systemctl: error while loading shared libraries: libsystemd-shared-253.so: cannot open shared object file: No such file or directory
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp95x9ob7v ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp95x9ob7v
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Aug  8 19:10:39 2023 - INFO  - End to restore the test environment.
