+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Thu Sep 21 22:34:29 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL 'fftw gcc'
+ pkgs='fftw gcc'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'fftw gcc' --node 1 --tempfile ''
Thu Sep 21 22:35:11 2023 - INFO  - pkgs:(fftw gcc) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ mkdir -p ./tmp
++ rpm -qa fftw
++ awk -F - '{print $2}'
+ VERSION=3.3.10
+ echo '(fftw-3.3.8 fftw_wisdom #x4be12fff #x7b2df9b2 #xa5975329 #x385b0041
    (fftw_codelet_n1_16 0 #x12345 #x22222 #x0 #x4396230b #x936694df #xa8dfdff3 #x77777777)
    )'
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Thu Sep 21 22:35:20 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu Sep 21 22:35:22 2023 - INFO  - Start to run test.
+ fftw-wisdom-to-conf -h
+ grep -q Usage
+ CHECK_RESULT 0 0 0 'Check fftw-wisdom-to-conf -h failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fftw-wisdom-to-conf -h failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fftw-wisdom-to-conf --help
+ grep -q Usage
+ CHECK_RESULT 0 0 0 'Check fftw-wisdom-to-conf --help failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fftw-wisdom-to-conf --help failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fftw-wisdom-to-conf -V
+ grep -q 3.3.10
+ CHECK_RESULT 0 0 0 'Check fftw-wisdom-to-conf -V failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fftw-wisdom-to-conf -V failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fftw-wisdom-to-conf --version
+ grep -q 3.3.10
+ CHECK_RESULT 0 0 0 'Check fftw-wisdom-to-conf --version failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check fftw-wisdom-to-conf --version failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fftw-wisdom-to-conf
+ grep -q fftw_configure_planner
fftw-wisdom-to-conf: invalid wisdom
+ CHECK_RESULT 1 0 0 'Check fftw-wisdom-to-conf output failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check fftw-wisdom-to-conf output failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check fftw-wisdom-to-conf output failed.'
+ LOG_ERROR 'Check fftw-wisdom-to-conf output failed.'
+ message='Check fftw-wisdom-to-conf output failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check fftw-wisdom-to-conf output failed.'
Thu Sep 21 22:35:24 2023 - ERROR - Check fftw-wisdom-to-conf output failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fftw_fftw-wisdom-to-conf.sh line 45'
+ message='oe_test_fftw_fftw-wisdom-to-conf.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fftw_fftw-wisdom-to-conf.sh line 45'
Thu Sep 21 22:35:25 2023 - ERROR - oe_test_fftw_fftw-wisdom-to-conf.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Thu Sep 21 22:35:27 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Sep 21 22:35:28 2023 - ERROR - failed to execute the case.
+ exit 1
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Thu Sep 21 22:35:30 2023 - INFO  - Start to restore the test environment.
+ rm -rf ./tmp
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Thu Sep 21 22:35:31 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Thu Sep 21 22:35:33 2023 - INFO  - End to restore the test environment.
