+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n '' ']'
+ trap POST_TEST_DEFAULT EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Fri Aug 11 00:23:45 2023 - INFO  - Start to prepare the database config.
++ date +%Y%m%d%H%M%S
+ cur_date=20230811002345
++ CREATE_VG
+++ date +%Y%m%d%H%M%S
++ cur_date=20230811002345
+++ lsblk
+++ grep disk
+++ awk '{print $1}'
+++ tail -n 1
++ free_disk=vdt
++ disk_name=/dev/vdt
++ pvcreate /dev/vdt -f
++ [[ 5 -eq 0 ]]
+++ pvcreate /dev/vdt
+++ grep test_vggroup
+++ cut -d '"' -f 4
++ vggroup=test_vggroup20230811002108
++ printf test_vggroup20230811002108
+ vggroup=test_vggroup20230811002108
+ lv=test_lv20230811002345
+ lvcreate -n test_lv20230811002345 -L 2G test_vggroup20230811002108 -y
  Volume group "test_vggroup20230811002108" has insufficient free space (124 extents): 512 required.
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Fri Aug 11 00:23:48 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Aug 11 00:23:50 2023 - INFO  - Start to run test.
+ mkfs.xfs /dev/test_vggroup20230811002108/test_lv20230811002345
oe_test_FSIO_create_xfs.sh: line 32: mkfs.xfs: command not found
+ CHECK_RESULT 127 0 0 'mkfs.xfs failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='mkfs.xfs failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'mkfs.xfs failed'
+ LOG_ERROR 'mkfs.xfs failed'
+ message='mkfs.xfs failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'mkfs.xfs failed'
Fri Aug 11 00:23:51 2023 - ERROR - mkfs.xfs failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_create_xfs.sh line 33'
+ message='oe_test_FSIO_create_xfs.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_create_xfs.sh line 33'
Fri Aug 11 00:23:53 2023 - ERROR - oe_test_FSIO_create_xfs.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ blkid
+ grep /dev/mapper/test_vggroup20230811002108-test_lv20230811002345
+ grep 'TYPE="xfs"'
+ CHECK_RESULT 1 0 0 'Check lv infos failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check lv infos failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check lv infos failed'
+ LOG_ERROR 'Check lv infos failed'
+ message='Check lv infos failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Check lv infos failed'
Fri Aug 11 00:23:55 2023 - ERROR - Check lv infos failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_create_xfs.sh line 35'
+ message='oe_test_FSIO_create_xfs.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_create_xfs.sh line 35'
Fri Aug 11 00:23:56 2023 - ERROR - oe_test_FSIO_create_xfs.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Aug 11 00:23:58 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Aug 11 00:23:59 2023 - ERROR - failed to execute the case.
+ exit 2
+ POST_TEST_DEFAULT
+ LOG_INFO 'oe_test_FSIO_create_xfs.sh post_test'
+ message='oe_test_FSIO_create_xfs.sh post_test'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'oe_test_FSIO_create_xfs.sh post_test'
Fri Aug 11 00:24:00 2023 - INFO  - oe_test_FSIO_create_xfs.sh post_test
