+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Wed Oct 18 12:35:16 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL vdo
+ pkgs=vdo
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs vdo --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp3p6socy6
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp3p6socy6
+ dd if=/dev/zero of=vdo_test_device bs=1M count=10240
10240+0 records in
10240+0 records out
10737418240 bytes (11 GB, 10 GiB) copied, 156.435 s, 68.6 MB/s
+ losetup /dev/loop0 vdo_test_device
+ vdo create -n my_vdo_volume --device /dev/loop0
vdo: WARNING - unable to determine VDO service my_vdo_volume instance number: [Errno 2] No such file or directory: '/sys/kvdo/my_vdo_volume/instance'
vdo: WARNING - unable to determine VDO service my_vdo_volume instance number: [Errno 2] No such file or directory: '/sys/kvdo/my_vdo_volume/instance'
Creating VDO my_vdo_volume
      Logical blocks defaulted to 1569686 blocks.
      The VDO volume can address 6 GB in 3 data slabs, each 2 GB.
      It can grow to address at most 16 TB of physical storage in 8192 slabs.
      If a larger maximum size might be needed, use bigger slabs.
Starting VDO my_vdo_volume
Starting compression on VDO my_vdo_volume
VDO instance 0 volume is ready at /dev/mapper/my_vdo_volume
+ touch /var/log/vdo_status.log
+ LOG_INFO 'End to prepare the test environment'
+ message='End to prepare the test environment'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment'
Wed Oct 18 12:38:29 2023 - INFO  - End to prepare the test environment
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run testcase:oe_test_vdo_10.'
+ message='Start to run testcase:oe_test_vdo_10.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run testcase:oe_test_vdo_10.'
Wed Oct 18 12:38:30 2023 - INFO  - Start to run testcase:oe_test_vdo_10.
+ vdo status --help
+ grep 'usage: vdo status'
usage: vdo status [-h] [-a | -n <volume>] [--pending] [-f <file>]
+ CHECK_RESULT 0 0 0 'Check vdo status --help failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check vdo status --help failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vdo status -a
+ grep 'VDO status:'
VDO status:
+ CHECK_RESULT 0 0 0 'Check vdo status -a failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check vdo status -a failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vdo status -n my_vdo_volume
+ grep 'VDO status:'
VDO status:
+ CHECK_RESULT 0 0 0 'Check vdo status -n failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check vdo status -n failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vdo status --verbose -n my_vdo_volume
+ grep 'VDO status:'
VDO status:
+ CHECK_RESULT 0 0 0 'Check vdo status --verbose failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check vdo status --verbose failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vdo status -n my_vdo_volume -f /etc/vdoconf.yml
+ grep 'VDO status:'
VDO status:
+ CHECK_RESULT 0 0 0 'Check vdo status -f failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check vdo status -f failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vdo status -n my_vdo_volume --logfile /var/log/vdo_status.log
+ grep 'VDO status:'
VDO status:
+ CHECK_RESULT 0 0 0 'Check vdo status --logfile failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check vdo status --logfile failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed Oct 18 12:39:16 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Wed Oct 18 12:39:17 2023 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed Oct 18 12:39:17 2023 - INFO  - Start to restore the test environment.
+ sudo rm /var/log/vdo_status.log
+ vdo remove -n my_vdo_volume
Removing VDO my_vdo_volume
Stopping VDO my_vdo_volume
+ losetup -d /dev/loop0
+ rm vdo_test_device -f
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp3p6socy6 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp3p6socy6
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed Oct 18 12:39:39 2023 - INFO  - End to restore the test environment.
