+ source common/common_pcp.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Fri Sep 22 05:56:41 2023 - INFO  - Start to prepare the test environment.
+ deploy_env
+ DNF_INSTALL pcp
+ pkgs=pcp
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs pcp --node 1 --tempfile ''
Fri Sep 22 05:57:01 2023 - INFO  - pkgs:(pcp) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ systemctl enable pmcd
+ systemctl start pmcd
+ systemctl enable pmlogger
+ systemctl start pmlogger
Job for pmlogger.service failed because the control process exited with error code.
See "systemctl status pmlogger.service" and "journalctl -xeu pmlogger.service" for details.
+ SLEEP_WAIT 10
+ wait_time=10
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 10 --cmd '' --mode 1
++ hostname
+ host_name=openeuler-riscv64
++ rpm -qa pcp
++ awk -F - '{print $2}'
+ pcp_version=5.3.7
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Fri Sep 22 05:57:45 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Sep 22 05:57:47 2023 - INFO  - Start to run test.
+ /usr/libexec/pcp/bin/pmlogger_daily -p
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ /usr/libexec/pcp/bin/pmlogger_daily -r
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogger_daily_02.sh line 32'
+ message='oe_test_pmlogger_daily_02.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogger_daily_02.sh line 32'
Fri Sep 22 05:58:04 2023 - ERROR - oe_test_pmlogger_daily_02.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ /usr/libexec/pcp/bin/pmlogger_daily -R
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogger_daily_02.sh line 34'
+ message='oe_test_pmlogger_daily_02.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogger_daily_02.sh line 34'
Fri Sep 22 05:58:17 2023 - ERROR - oe_test_pmlogger_daily_02.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ /usr/libexec/pcp/bin/pmlogger_daily -s 100
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogger_daily_02.sh line 36'
+ message='oe_test_pmlogger_daily_02.sh line 36'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogger_daily_02.sh line 36'
Fri Sep 22 05:58:31 2023 - ERROR - oe_test_pmlogger_daily_02.sh line 36
+ '[' 0 -eq 1 ']'
+ return 0
+ /usr/libexec/pcp/bin/pmlogger_daily -x 5
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogger_daily_02.sh line 38'
+ message='oe_test_pmlogger_daily_02.sh line 38'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogger_daily_02.sh line 38'
Fri Sep 22 05:58:44 2023 - ERROR - oe_test_pmlogger_daily_02.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Sep 22 05:58:46 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Sep 22 05:58:47 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Sep 22 05:58:48 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Fri Sep 22 05:58:50 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Sep 22 05:58:51 2023 - INFO  - End to restore the test environment.
