+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Mon Sep 11 18:38:28 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL 'xinetd tftp tftp-server net-tools'
+ pkgs='xinetd tftp tftp-server net-tools'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'xinetd tftp tftp-server net-tools' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpvred9pm2
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpvred9pm2
+ ifconfig inet6 add 2001:250:250:250:250:250:250:222/64
SIOGIFINDEX: No such device
+ route -A inet6 add default gw 2001:250:250:250::1 dev
Usage: inet6_route [-vF] del Target
       inet6_route [-vF] add Target [gw Gw] [metric M] [[dev] If]
       inet6_route [-FC] flush      NOT supported
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ ping6 -c 3 2001:250:250:250:250:250:250:222
PING 2001:250:250:250:250:250:250:222(2001:250:250:250:250:250:250:222) 56 data bytes

--- 2001:250:250:250:250:250:250:222 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2027ms

+ sed -i 's/flags.*/flags = IPV6/' /etc/xinetd.d/tftp
+ sed -i 's/disable.*/disable = no/' /etc/xinetd.d/tftp
+ sed -i 's/server_args.*/server_args         = -s \/tmp\/tftpboot -c/' /etc/xinetd.d/tftp
+ getenforce
+ grep Enforcing
+ systemctl status firewalld
+ grep failed
Unit firewalld.service could not be found.
+ mkdir /tmp/tftpboot
+ systemctl restart xinetd
+ systemctl restart tftp
+ echo hello1
+ chmod 644 /tmp/tftpboot/hello1.txt
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ systemctl restart xinetd
+ systemctl restart tftp
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Mon Sep 11 18:39:37 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Mon Sep 11 18:39:38 2023 - INFO  - Start to run test.
+ tftp -6 2001:250:250:250:250:250:250:222 -c get hello1.txt
Transfer timed out.
+ CHECK_RESULT 69 0 0 'Failed to execute tftp get'
+ actual_result=69
+ expect_result=0
+ mode=0
+ error_log='Failed to execute tftp get'
+ exit_mode=0
+ '[' -z 69 ']'
+ '[' 0 -eq 0 ']'
+ test 69x '!=' 0x
+ test -n 'Failed to execute tftp get'
+ LOG_ERROR 'Failed to execute tftp get'
+ message='Failed to execute tftp get'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to execute tftp get'
Mon Sep 11 18:40:03 2023 - ERROR - Failed to execute tftp get
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_tftp_ipv6.sh line 49'
+ message='oe_test_tftp_ipv6.sh line 49'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_tftp_ipv6.sh line 49'
Mon Sep 11 18:40:04 2023 - ERROR - oe_test_tftp_ipv6.sh line 49
+ '[' 0 -eq 1 ']'
+ return 0
+ grep hello1 hello1.txt
+ CHECK_RESULT 1 0 0 'Failed to find hello1'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to find hello1'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to find hello1'
+ LOG_ERROR 'Failed to find hello1'
+ message='Failed to find hello1'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to find hello1'
Mon Sep 11 18:40:04 2023 - ERROR - Failed to find hello1
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_tftp_ipv6.sh line 51'
+ message='oe_test_tftp_ipv6.sh line 51'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_tftp_ipv6.sh line 51'
Mon Sep 11 18:40:05 2023 - ERROR - oe_test_tftp_ipv6.sh line 51
+ '[' 0 -eq 1 ']'
+ return 0
+ echo hello2
+ chmod 777 hello2.txt
+ chmod 777 /tmp/tftpboot
+ tftp -6 2001:250:250:250:250:250:250:222 -c put hello2.txt
Transfer timed out.
+ CHECK_RESULT 69 0 0 'Failed to execute put'
+ actual_result=69
+ expect_result=0
+ mode=0
+ error_log='Failed to execute put'
+ exit_mode=0
+ '[' -z 69 ']'
+ '[' 0 -eq 0 ']'
+ test 69x '!=' 0x
+ test -n 'Failed to execute put'
+ LOG_ERROR 'Failed to execute put'
+ message='Failed to execute put'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to execute put'
Mon Sep 11 18:40:30 2023 - ERROR - Failed to execute put
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_tftp_ipv6.sh line 56'
+ message='oe_test_tftp_ipv6.sh line 56'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_tftp_ipv6.sh line 56'
Mon Sep 11 18:40:31 2023 - ERROR - oe_test_tftp_ipv6.sh line 56
+ '[' 0 -eq 1 ']'
+ return 0
+ grep hello2 /tmp/tftpboot/hello2.txt
grep: /tmp/tftpboot/hello2.txt: No such file or directory
+ CHECK_RESULT 2 0 0 'Failed to find hello2'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Failed to find hello2'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Failed to find hello2'
+ LOG_ERROR 'Failed to find hello2'
+ message='Failed to find hello2'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to find hello2'
Mon Sep 11 18:40:31 2023 - ERROR - Failed to find hello2
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_tftp_ipv6.sh line 58'
+ message='oe_test_tftp_ipv6.sh line 58'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_tftp_ipv6.sh line 58'
Mon Sep 11 18:40:32 2023 - ERROR - oe_test_tftp_ipv6.sh line 58
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Mon Sep 11 18:40:32 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Mon Sep 11 18:40:33 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Mon Sep 11 18:40:33 2023 - INFO  - Start to restore the test environment.
+ rm -rf /tmp/tftpboot hello1.txt hello2.txt
+ getenforce
+ grep Permissive
+ ifconfig inet6 del 2001:250:250:250:250:250:250:222/64
SIOGIFINDEX: No such device
+ route -A inet6 del default gw 2001:250:250:250::1 dev
Usage: inet6_route [-vF] del Target
       inet6_route [-vF] add Target [gw Gw] [metric M] [[dev] If]
       inet6_route [-FC] flush      NOT supported
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpvred9pm2 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpvred9pm2
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Mon Sep 11 18:40:47 2023 - INFO  - End to restore the test environment.
