+ source ../common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ grep expect
+ rpm -qa
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Thu Sep 21 22:34:22 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL pesign
+ pkgs=pesign
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs pesign --node 1 --tempfile ''
Thu Sep 21 22:35:06 2023 - INFO  - pkgs:(pesign) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ mkdir /etc/pki/pesign
mkdir: cannot create directory ‘/etc/pki/pesign’: File exists
+ expect
spawn certutil -d /etc/pki/pesign/ -N
Enter Password or Pin for "NSS Certificate DB":+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Thu Sep 21 22:35:38 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Thu Sep 21 22:35:40 2023 - INFO  - Start testing...
+ test_execution pesign.service
+ service=pesign.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-09-21 22:35:40'
+ test_restart pesign.service
+ service=pesign.service
+ systemctl restart pesign.service
Job for pesign.service failed because the control process exited with error code.
See "systemctl status pesign.service" and "journalctl -xeu pesign.service" for details.
+ CHECK_RESULT 1 0 0 'pesign.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='pesign.service restart failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'pesign.service restart failed'
+ LOG_ERROR 'pesign.service restart failed'
+ message='pesign.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pesign.service restart failed'
Thu Sep 21 22:35:46 2023 - ERROR - pesign.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Thu Sep 21 22:35:47 2023 - ERROR - ../common/common_lib.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status pesign.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'pesign.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='pesign.service restart failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'pesign.service restart failed'
+ LOG_ERROR 'pesign.service restart failed'
+ message='pesign.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pesign.service restart failed'
Thu Sep 21 22:35:56 2023 - ERROR - pesign.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Thu Sep 21 22:35:57 2023 - ERROR - ../common/common_lib.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl stop pesign.service
+ CHECK_RESULT 0 0 0 'pesign.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='pesign.service stop failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status pesign.service
+ grep 'Active: inactive'
+ CHECK_RESULT 1 0 0 'pesign.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='pesign.service stop failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'pesign.service stop failed'
+ LOG_ERROR 'pesign.service stop failed'
+ message='pesign.service stop failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pesign.service stop failed'
Thu Sep 21 22:36:06 2023 - ERROR - pesign.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Thu Sep 21 22:36:08 2023 - ERROR - ../common/common_lib.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start pesign.service
Job for pesign.service failed because the control process exited with error code.
See "systemctl status pesign.service" and "journalctl -xeu pesign.service" for details.
+ CHECK_RESULT 1 0 0 'pesign.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='pesign.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'pesign.service start failed'
+ LOG_ERROR 'pesign.service start failed'
+ message='pesign.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pesign.service start failed'
Thu Sep 21 22:36:13 2023 - ERROR - pesign.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Thu Sep 21 22:36:15 2023 - ERROR - ../common/common_lib.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status pesign.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'pesign.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='pesign.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'pesign.service start failed'
+ LOG_ERROR 'pesign.service start failed'
+ message='pesign.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pesign.service start failed'
Thu Sep 21 22:36:23 2023 - ERROR - pesign.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Thu Sep 21 22:36:25 2023 - ERROR - ../common/common_lib.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ test_enabled pesign.service
+ service=pesign.service
++ systemctl is-enabled pesign.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ systemctl enable pesign.service
++ grep 'Created symlink'
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/pesign.service
+ find /etc/systemd/system/multi-user.target.wants/pesign.service
/etc/systemd/system/multi-user.target.wants/pesign.service
+ CHECK_RESULT 0 0 0 'pesign.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='pesign.service enable failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable pesign.service
Removed "/etc/systemd/system/multi-user.target.wants/pesign.service".
+ find /etc/systemd/system/multi-user.target.wants/pesign.service
find: ‘/etc/systemd/system/multi-user.target.wants/pesign.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'pesign.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='pesign.service disable failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2023-09-21 22:35:40' -u pesign.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
Sep 21 22:35:41 openeuler-riscv64 systemd[1]: pesign.service: Main process exited, code=exited, status=1/FAILURE
Sep 21 22:35:44 openeuler-riscv64 systemd[1]: pesign.service: Failed with result 'exit-code'.
Sep 21 22:35:44 openeuler-riscv64 systemd[1]: Failed to start Pesign signing daemon.
Sep 21 22:36:09 openeuler-riscv64 systemd[1]: pesign.service: Main process exited, code=exited, status=1/FAILURE
Sep 21 22:36:12 openeuler-riscv64 systemd[1]: pesign.service: Failed with result 'exit-code'.
Sep 21 22:36:12 openeuler-riscv64 systemd[1]: Failed to start Pesign signing daemon.
+ CHECK_RESULT 0 0 1 'There is an error message for the log of pesign.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of pesign.service'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of pesign.service'
+ LOG_ERROR 'There is an error message for the log of pesign.service'
+ message='There is an error message for the log of pesign.service'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of pesign.service'
Thu Sep 21 22:36:45 2023 - ERROR - There is an error message for the log of pesign.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Thu Sep 21 22:36:46 2023 - ERROR - ../common/common_lib.sh line 28
+ '[' 0 -eq 1 ']'
+ return 0
+ test_reload pesign.service
+ service=pesign.service
+ systemctl start pesign.service
Job for pesign.service failed because the control process exited with error code.
See "systemctl status pesign.service" and "journalctl -xeu pesign.service" for details.
+ systemctl reload pesign.service
+ grep 'Job type reload is not applicable'
Failed to reload pesign.service: Job type reload is not applicable for unit pesign.service.
+ CHECK_RESULT 0 0 0 'Job type reload is not applicable for unit pesign.service'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit pesign.service'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl status pesign.service
+ grep 'Active: active'
+ systemctl status pesign.service
+ grep 'inactive (dead)'
+ return 1
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Thu Sep 21 22:36:53 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 6
+ test 6 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Sep 21 22:36:54 2023 - ERROR - failed to execute the case.
+ exit 6
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Thu Sep 21 22:36:56 2023 - INFO  - start environment cleanup.
+ systemctl stop pesign.service
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Thu Sep 21 22:36:57 2023 - WARN  - no thing to do.
+ return 0
+ rm -rf /etc/pki/pesign log
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Thu Sep 21 22:36:59 2023 - INFO  - Finish environment cleanup!
