+ source common/common_pcp.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Fri Sep 22 05:18:05 2023 - INFO  - Start to prepare the test environment.
+ deploy_env
+ DNF_INSTALL pcp
+ pkgs=pcp
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs pcp --node 1 --tempfile ''
Fri Sep 22 05:18:26 2023 - INFO  - pkgs:(pcp) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ systemctl enable pmcd
+ systemctl start pmcd
+ systemctl enable pmlogger
+ systemctl start pmlogger
Job for pmlogger.service failed because the control process exited with error code.
See "systemctl status pmlogger.service" and "journalctl -xeu pmlogger.service" for details.
+ SLEEP_WAIT 10
+ wait_time=10
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 10 --cmd '' --mode 1
++ hostname
+ host_name=openeuler-riscv64
++ rpm -qa pcp
++ awk -F - '{print $2}'
+ pcp_version=5.3.7
++ pcp -h openeuler-riscv64
++ grep 'primary logger:'
++ awk -F: '{print $NF}'
+ archive_data=
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Fri Sep 22 05:19:23 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Sep 22 05:19:24 2023 - INFO  - Start to run test.
+ pmlogconf -c configfile
pmlogconf: Cannot connect to pmcd on host "local:": Connection refused
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogconf_pmlogsize.sh line 31'
+ message='oe_test_pmlogconf_pmlogsize.sh line 31'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogconf_pmlogsize.sh line 31'
Fri Sep 22 05:19:26 2023 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 31
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'log advisory on default' configfile
grep: configfile: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogconf_pmlogsize.sh line 33'
+ message='oe_test_pmlogconf_pmlogsize.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogconf_pmlogsize.sh line 33'
Fri Sep 22 05:19:27 2023 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ rm -f configfile
+ pmlogconf -d . configfile
pmlogconf: Cannot connect to pmcd on host "local:": Connection refused
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogconf_pmlogsize.sh line 36'
+ message='oe_test_pmlogconf_pmlogsize.sh line 36'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogconf_pmlogsize.sh line 36'
Fri Sep 22 05:19:29 2023 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 36
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'allow local' configfile
grep: configfile: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogconf_pmlogsize.sh line 38'
+ message='oe_test_pmlogconf_pmlogsize.sh line 38'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogconf_pmlogsize.sh line 38'
Fri Sep 22 05:19:31 2023 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ rm -f configfile
+ pmlogconf -h openeuler-riscv64 configfile
pmlogconf: Cannot connect to pmcd on host "openeuler-riscv64": Connection refused
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogconf_pmlogsize.sh line 41'
+ message='oe_test_pmlogconf_pmlogsize.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogconf_pmlogsize.sh line 41'
Fri Sep 22 05:19:32 2023 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f configfile
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogconf_pmlogsize.sh line 43'
+ message='oe_test_pmlogconf_pmlogsize.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogconf_pmlogsize.sh line 43'
Fri Sep 22 05:19:34 2023 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ rm -f configfile
+ pmlogconf -qrv configfile
+ grep /var/lib/pcp/config/pmlogconf
pmlogconf: Cannot connect to pmcd on host "local:": Connection refused
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogconf_pmlogsize.sh line 46'
+ message='oe_test_pmlogconf_pmlogsize.sh line 46'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogconf_pmlogsize.sh line 46'
Fri Sep 22 05:19:35 2023 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f configfile
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogconf_pmlogsize.sh line 48'
+ message='oe_test_pmlogconf_pmlogsize.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogconf_pmlogsize.sh line 48'
Fri Sep 22 05:19:37 2023 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ rm -f configfile
+ pmlogsize -d
+ grep data
Error: no archive specified

Usage: pmlogsize [options] archive

Options:
  -d, --detail          detailed output (per metric and per indom)
  -r, --replication     report replicated metric values and instances
  -v, --verbose         verbose output
  -x thres, --threshold=thres
                        cull detailed report after thres % of space reported
  -?, --help            show this usage message and exit
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogconf_pmlogsize.sh line 51'
+ message='oe_test_pmlogconf_pmlogsize.sh line 51'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogconf_pmlogsize.sh line 51'
Fri Sep 22 05:19:38 2023 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 51
+ '[' 0 -eq 1 ']'
+ return 0
+ pmlogsize -r
+ grep dups
Error: no archive specified

Usage: pmlogsize [options] archive

Options:
  -d, --detail          detailed output (per metric and per indom)
  -r, --replication     report replicated metric values and instances
  -v, --verbose         verbose output
  -x thres, --threshold=thres
                        cull detailed report after thres % of space reported
  -?, --help            show this usage message and exit
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogconf_pmlogsize.sh line 53'
+ message='oe_test_pmlogconf_pmlogsize.sh line 53'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogconf_pmlogsize.sh line 53'
Fri Sep 22 05:19:40 2023 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 53
+ '[' 0 -eq 1 ']'
+ return 0
+ pmlogsize -v
+ grep PMID
Error: no archive specified

Usage: pmlogsize [options] archive

Options:
  -d, --detail          detailed output (per metric and per indom)
  -r, --replication     report replicated metric values and instances
  -v, --verbose         verbose output
  -x thres, --threshold=thres
                        cull detailed report after thres % of space reported
  -?, --help            show this usage message and exit
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogconf_pmlogsize.sh line 55'
+ message='oe_test_pmlogconf_pmlogsize.sh line 55'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogconf_pmlogsize.sh line 55'
Fri Sep 22 05:19:41 2023 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 55
+ '[' 0 -eq 1 ']'
+ return 0
+ pmlogsize -x 60
+ grep index
Error: no archive specified

Usage: pmlogsize [options] archive

Options:
  -d, --detail          detailed output (per metric and per indom)
  -r, --replication     report replicated metric values and instances
  -v, --verbose         verbose output
  -x thres, --threshold=thres
                        cull detailed report after thres % of space reported
  -?, --help            show this usage message and exit
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pmlogconf_pmlogsize.sh line 57'
+ message='oe_test_pmlogconf_pmlogsize.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pmlogconf_pmlogsize.sh line 57'
Fri Sep 22 05:19:43 2023 - ERROR - oe_test_pmlogconf_pmlogsize.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Sep 22 05:19:44 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 12
+ test 12 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Sep 22 05:19:46 2023 - ERROR - failed to execute the case.
+ exit 12
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Sep 22 05:19:47 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Fri Sep 22 05:19:48 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Sep 22 05:19:50 2023 - INFO  - End to restore the test environment.
