+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Tue Sep 12 10:19:42 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL python3-pip
+ pkgs=python3-pip
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs python3-pip --node 1 --tempfile ''
Tue Sep 12 10:19:42 2023 - INFO  - pkgs:(python3-pip) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Tue Sep 12 10:19:42 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Sep 12 10:19:42 2023 - INFO  - Start to run test.
+ pip3 install --user requests
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple
Collecting requests
  Downloading https://repo.huaweicloud.com/repository/pypi/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 4.9 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2 (from requests)
  Downloading https://repo.huaweicloud.com/repository/pypi/packages/18/36/7ae10a3dd7f9117b61180671f8d1e4802080cca88ad40aaabd3dad8bab0e/charset_normalizer-3.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (197 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.3/197.3 kB 4.2 MB/s eta 0:00:00
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests) (3.4)
Collecting urllib3<3,>=1.21.1 (from requests)
  Downloading https://repo.huaweicloud.com/repository/pypi/packages/4b/1d/f8383ef593114755429c307449e7717b87044b3bcd5f7860b89b1f759e34/urllib3-2.0.2-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.2/123.2 kB 7.9 MB/s eta 0:00:00
Collecting certifi>=2017.4.17 (from requests)
  Downloading https://repo.huaweicloud.com/repository/pypi/packages/1d/38/fa96a426e0c0e68aabc68e896584b83ad1eec779265a028e156ce509630e/certifi-2022.9.24-py3-none-any.whl (161 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB 3.7 MB/s eta 0:00:00
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
Installing collected packages: urllib3, charset-normalizer, certifi, requests
  WARNING: The script normalizer is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed certifi-2022.9.24 charset-normalizer-3.1.0 requests-2.31.0 urllib3-2.0.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
+ CHECK_RESULT 0 0 0 'Failed to execute pip3 install --user'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed to execute pip3 install --user'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ test -d /root/.local/lib/python3.11/site-packages/requests
+ CHECK_RESULT 0 0 0 'Failed to find site-packages/requests in /root'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed to find site-packages/requests in /root'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pip3 uninstall requests -y
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
  Successfully uninstalled requests-2.31.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ pip3 install --root /tmp requests
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple
Collecting requests
  Using cached https://repo.huaweicloud.com/repository/pypi/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl (62 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/.local/lib/python3.11/site-packages (from requests) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/.local/lib/python3.11/site-packages (from requests) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /root/.local/lib/python3.11/site-packages (from requests) (2022.9.24)
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
Installing collected packages: requests
Successfully installed requests-2.31.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
+ CHECK_RESULT 0 0 0 'Failed to execute pip3 install --root'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed to execute pip3 install --root'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ test -d /tmp/usr/local/lib/python3.11/site-packages/requests
+ CHECK_RESULT 0 0 0 'Failed to find site-packages/requests in /tmp'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed to find site-packages/requests in /tmp'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ rm -rf /tmp/usr
+ pip3 install --prefix /tmp requests
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple
Collecting requests
  Using cached https://repo.huaweicloud.com/repository/pypi/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl (62 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/.local/lib/python3.11/site-packages (from requests) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/.local/lib/python3.11/site-packages (from requests) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /root/.local/lib/python3.11/site-packages (from requests) (2022.9.24)
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
Installing collected packages: requests
Successfully installed requests-2.31.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
+ CHECK_RESULT 0 0 0 'Failed to execute pip3 install --prefix'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed to execute pip3 install --prefix'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ test -d /tmp/lib/python3.11/site-packages/requests
+ CHECK_RESULT 0 0 0 'Failed to find requests in /tmp'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed to find requests in /tmp'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep charset-normalizer
+ pip3 list
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
charset-normalizer 3.1.0
+ CHECK_RESULT 0 0 0 'Failed to execute pip3 list'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed to execute pip3 list'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pip3 uninstall -y requests charset-normalizer
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping requests as it is not installed.
Found existing installation: charset-normalizer 3.1.0
Uninstalling charset-normalizer-3.1.0:
  Successfully uninstalled charset-normalizer-3.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ pip3 install --no-deps requests
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple
Collecting requests
  Using cached https://repo.huaweicloud.com/repository/pypi/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl (62 kB)
Installing collected packages: requests
Successfully installed requests-2.31.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
+ CHECK_RESULT 0 0 0 'Failed to execute pip3 install --no-deps'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed to execute pip3 install --no-deps'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pip3 list
+ grep charset-normalizer
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
+ CHECK_RESULT 1 0 1 'Succeed to execute pip3 list'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='Succeed to execute pip3 list'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ grep Successfully
+ pip3 install --force-reinstall requests
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
      Successfully uninstalled urllib3-2.0.2
      Successfully uninstalled certifi-2022.9.24
      Successfully uninstalled requests-2.31.0
Successfully installed certifi-2022.9.24 charset-normalizer-3.1.0 idna-3.4 requests-2.31.0 urllib3-2.0.2
+ CHECK_RESULT 0 0 0 'Failed to execute pip3 install --force-reinstall'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed to execute pip3 install --force-reinstall'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pip3 install --upgrade requests
+ grep already
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
Requirement already satisfied: requests in /usr/local/lib/python3.11/site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib64/python3.11/site-packages (from requests) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/site-packages (from requests) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/site-packages (from requests) (2022.9.24)
+ CHECK_RESULT 0 0 0 'Failed to execute pip3 install --upgrade'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed to execute pip3 install --upgrade'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pip3 uninstall -y requests
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
  Successfully uninstalled requests-2.31.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ pip3 install --upgrade requests
+ grep Successfully
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
Successfully installed requests-2.31.0
+ CHECK_RESULT 0 0 0 'Failed to repead execute pip3 install --upgrade'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed to repead execute pip3 install --upgrade'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pip3 install --ignore-installed requests
+ grep 'Installing collected packages'
+ grep certifi
+ grep urllib3
+ grep requests
+ grep charset-normalizer
+ grep idna
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
+ CHECK_RESULT 0 0 0 'Failed to execute pip3 install --ignore-installed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed to execute pip3 install --ignore-installed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Sep 12 10:19:53 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Tue Sep 12 10:19:53 2023 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Sep 12 10:19:53 2023 - INFO  - Start to restore the test environment.
+ rm -rf /tmp/lib /tmp/local
+ pip3 uninstall -y requests urllib3 idna charset-normalizer certifi
WARNING: Skipping /usr/lib64/python3.11/site-packages/pycairo-1.24.0-py3.11.egg-info due to invalid metadata entry 'name'
Found existing installation: requests 2.31.0
Uninstalling requests-2.31.0:
  Successfully uninstalled requests-2.31.0
Found existing installation: urllib3 2.0.2
Uninstalling urllib3-2.0.2:
  Successfully uninstalled urllib3-2.0.2
Found existing installation: idna 3.4
Uninstalling idna-3.4:
  Successfully uninstalled idna-3.4
Found existing installation: charset-normalizer 3.1.0
Uninstalling charset-normalizer-3.1.0:
  Successfully uninstalled charset-normalizer-3.1.0
Found existing installation: certifi 2022.9.24
Uninstalling certifi-2022.9.24:
  Successfully uninstalled certifi-2022.9.24
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Tue Sep 12 10:19:53 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Sep 12 10:19:53 2023 - INFO  - End to restore the test environment.
