+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Thu May 25 16:27:46 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL 'libnetfilter_conntrack libnetfilter_conntrack-devel libnfnetlink-devel libmnl-devel'
+ pkgs='libnetfilter_conntrack libnetfilter_conntrack-devel libnfnetlink-devel libmnl-devel'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'libnetfilter_conntrack libnetfilter_conntrack-devel libnfnetlink-devel libmnl-devel' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpa6qp0xtg
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpa6qp0xtg
+ test -f ./test_api.log
+ test -f ./test_api
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Thu May 25 16:28:39 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu May 25 16:28:40 2023 - INFO  - Start to run test.
+ gcc -o test_api test_api.c -I../include /usr/lib64/libnetfilter_conntrack.so.3
In file included from /usr/include/errno.h:28,
                 from test_api.c:13:
/usr/include/bits/errno.h:26:11: fatal error: linux/errno.h: No such file or directory
   26 | # include <linux/errno.h>
      |           ^~~~~~~~~~~~~~~
compilation terminated.
+ test -f ./test_api
+ CHECK_RESULT 1 0 0 'compile test_api'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='compile test_api'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'compile test_api'
+ LOG_ERROR 'compile test_api'
+ message='compile test_api'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'compile test_api'
Thu May 25 16:28:42 2023 - ERROR - compile test_api
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libnetfilter_conntrack.sh line 33'
+ message='oe_test_libnetfilter_conntrack.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_libnetfilter_conntrack.sh line 33'
Thu May 25 16:28:43 2023 - ERROR - oe_test_libnetfilter_conntrack.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ ./test_api
oe_test_libnetfilter_conntrack.sh: line 34: ./test_api: No such file or directory
+ CHECK_RESULT 127 0 0 'test_api run'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='test_api run'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'test_api run'
+ LOG_ERROR 'test_api run'
+ message='test_api run'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'test_api run'
Thu May 25 16:28:44 2023 - ERROR - test_api run
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_libnetfilter_conntrack.sh line 35'
+ message='oe_test_libnetfilter_conntrack.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_libnetfilter_conntrack.sh line 35'
Thu May 25 16:28:45 2023 - ERROR - oe_test_libnetfilter_conntrack.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
++ cat test_api.log
++ grep -v '^=='
++ grep -v OK
++ wc -l
+ CHECK_RESULT 0 0 0 'check log of test_api'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='check log of test_api'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Thu May 25 16:28:46 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu May 25 16:28:47 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Thu May 25 16:28:48 2023 - INFO  - Start to restore the test environment.
+ test -f ./test_api.log
+ rm -rf ./test_api.log
+ test -f ./test_api
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpa6qp0xtg ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpa6qp0xtg
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Thu May 25 16:29:10 2023 - INFO  - End to restore the test environment.
