+ source common/common_dnf.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Thu May 25 17:19:19 2023 - INFO  - Start to prepare the test environment.
+ deploy_env
+ OLD_LANG=en_US.UTF-8
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ DNF_INSTALL time
+ pkgs=time
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs time --node 1 --tempfile ''
+ tmpfile2='Warning: failed loading '\''/etc/yum.repos.d/openEuler.repo'\'', skipping.
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".'
+ '[' -z '' ']'
+ tmpfile='Warning: failed loading '\''/etc/yum.repos.d/openEuler.repo'\'', skipping.
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".'
+ dnf list --available
+ awk '{print $1}'
+ grep 'arch\|x86_64'
+ awk -F . 'OFS="."{$NF="";print}'
+ awk '{print substr($0, 1, length($0)-1)}'
Warning: failed loading '/etc/yum.repos.d/openEuler.repo', skipping.
+ LOG_INFO 'Finish preparing the test environment.'
+ message='Finish preparing the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish preparing the test environment.'
Thu May 25 17:19:58 2023 - INFO  - Finish preparing the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu May 25 17:19:59 2023 - INFO  - Start to run test.
++ shuf -n1 pkg_list
+ pkg_name=
+ dnf install -y
+ grep 'Complete!'
usage: dnf install [-c [config file]] [-q] [-v] [--version]
                   [--installroot [path]] [--nodocs] [--noplugins]
                   [--enableplugin [plugin]] [--disableplugin [plugin]]
                   [--releasever RELEASEVER] [--setopt SETOPTS]
                   [--skip-broken] [-h] [--allowerasing] [-b | --nobest] [-C]
                   [-R [minutes]] [-d [debug level]] [--debugsolver]
                   [--showduplicates] [-e ERRORLEVEL] [--obsoletes]
                   [--rpmverbosity [debug level name]] [-y] [--assumeno]
                   [--enablerepo [repo]] [--disablerepo [repo] | --repo
                   [repo]] [--enable | --disable] [-x [package]]
                   [--disableexcludes [repo]] [--repofrompath [repo,path]]
                   [--noautoremove] [--nogpgcheck] [--color COLOR] [--refresh]
                   [-4] [-6] [--destdir DESTDIR] [--downloadonly]
                   [--comment COMMENT] [--bugfix] [--enhancement]
                   [--newpackage] [--security] [--advisory ADVISORY]
                   [--bz BUGZILLA] [--cve CVES]
                   [--sec-severity {Critical,Important,Moderate,Low}]
                   [--forcearch ARCH]
                   PACKAGE [PACKAGE ...]
dnf install: error: the following arguments are required: PACKAGE
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dnf_provides_randomwait.sh line 34'
+ message='oe_test_dnf_provides_randomwait.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dnf_provides_randomwait.sh line 34'
Thu May 25 17:20:06 2023 - ERROR - oe_test_dnf_provides_randomwait.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ rpm -ql
rpm: no arguments given for query
++ shuf -n1 file_list
+ file=
+ dnf provides
+ grep
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
usage: dnf provides [-c [config file]] [-q] [-v] [--version]
                    [--installroot [path]] [--nodocs] [--noplugins]
                    [--enableplugin [plugin]] [--disableplugin [plugin]]
                    [--releasever RELEASEVER] [--setopt SETOPTS]
                    [--skip-broken] [-h] [--allowerasing] [-b | --nobest] [-C]
                    [-R [minutes]] [-d [debug level]] [--debugsolver]
                    [--showduplicates] [-e ERRORLEVEL] [--obsoletes]
                    [--rpmverbosity [debug level name]] [-y] [--assumeno]
                    [--enablerepo [repo]] [--disablerepo [repo] | --repo
                    [repo]] [--enable | --disable] [-x [package]]
                    [--disableexcludes [repo]] [--repofrompath [repo,path]]
                    [--noautoremove] [--nogpgcheck] [--color COLOR]
                    [--refresh] [-4] [-6] [--destdir DESTDIR] [--downloadonly]
                    [--comment COMMENT] [--bugfix] [--enhancement]
                    [--newpackage] [--security] [--advisory ADVISORY]
                    [--bz BUGZILLA] [--cve CVES]
                    [--sec-severity {Critical,Important,Moderate,Low}]
                    [--forcearch ARCH]
                    PROVIDE [PROVIDE ...]
dnf provides: error: the following arguments are required: PROVIDE
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dnf_provides_randomwait.sh line 38'
+ message='oe_test_dnf_provides_randomwait.sh line 38'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dnf_provides_randomwait.sh line 38'
Thu May 25 17:20:12 2023 - ERROR - oe_test_dnf_provides_randomwait.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ dnf -q repoquery tree
+ grep check
+ CHECK_RESULT 1 1 0
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ dnf --quiet repoquery tree
+ grep check
+ CHECK_RESULT 1 1 0
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ grep riscv64
+ /usr/bin/time -f time-%U -o time.log dnf -R 3 repoquery
oe_test_dnf_provides_randomwait.sh: line 43: /usr/bin/time: No such file or directory
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dnf_provides_randomwait.sh line 44'
+ message='oe_test_dnf_provides_randomwait.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dnf_provides_randomwait.sh line 44'
Thu May 25 17:20:25 2023 - ERROR - oe_test_dnf_provides_randomwait.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
++ bc
+++ cat time.log
+++ awk -F - '{print $2}'
cat: time.log: No such file or directory
++ echo ' < 3'
(standard_in) 1: syntax error
+ ret=
+ CHECK_RESULT 1 0
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dnf_provides_randomwait.sh line 46'
+ message='oe_test_dnf_provides_randomwait.sh line 46'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dnf_provides_randomwait.sh line 46'
Thu May 25 17:20:26 2023 - ERROR - oe_test_dnf_provides_randomwait.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ dnf --refresh repoquery
+ grep kB
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dnf_provides_randomwait.sh line 48'
+ message='oe_test_dnf_provides_randomwait.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dnf_provides_randomwait.sh line 48'
Thu May 25 17:20:34 2023 - ERROR - oe_test_dnf_provides_randomwait.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of the test.'
+ message='End of the test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of the test.'
Thu May 25 17:20:35 2023 - INFO  - End of the test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 5
+ test 5 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu May 25 17:20:36 2023 - ERROR - failed to execute the case.
+ exit 5
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Thu May 25 17:20:38 2023 - INFO  - Start to restore the test environment.
+ clear_env
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ rm -rf pkg_list file_list time.log
+ DNF_REMOVE 1 ' time'
+ node=1
+ pkg_list=' time'
+ mode=0
+ [[ -z Warning: failed loading '/etc/yum.repos.d/openEuler.repo', skipping.
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d". ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs ' time' --tempfile 'Warning: failed loading '\''/etc/yum.repos.d/openEuler.repo'\'', skipping.
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".'
Traceback (most recent call last):
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 144, in rpm_remove
    with open(tmpfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Warning: failed loading \'/etc/yum.repos.d/openEuler.repo\', skipping.\nError: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".'
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End of restore the test environment.'
+ message='End of restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of restore the test environment.'
Thu May 25 17:20:44 2023 - INFO  - End of restore the test environment.
