+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Fri Sep 22 06:41:15 2023 - INFO  - Start environment preparation.
+ DNF_INSTALL nfs-utils
+ pkgs=nfs-utils
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs nfs-utils --node 1 --tempfile ''
Fri Sep 22 06:41:35 2023 - INFO  - pkgs:(nfs-utils) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ systemctl stop firewalld
+ iptables -F
+ SSH_CMD 'systemctl stop firewalld;iptables -F;yum install nfs-utils -y;
    mkdir /home/nfs;chmod 777 /home/nfs;mv /etc/exports /etc/exports.bak;
    echo '\''/home/nfs *(rw,sync,all_squash)'\'' >/etc/exports' 10.0.0.18 'openEuler12#$' root
+ cmd='systemctl stop firewalld;iptables -F;yum install nfs-utils -y;
    mkdir /home/nfs;chmod 777 /home/nfs;mv /etc/exports /etc/exports.bak;
    echo '\''/home/nfs *(rw,sync,all_squash)'\'' >/etc/exports'
+ remoteip=10.0.0.18
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'systemctl stop firewalld;iptables -F;yum install nfs-utils -y;
    mkdir /home/nfs;chmod 777 /home/nfs;mv /etc/exports /etc/exports.bak;
    echo '\''/home/nfs *(rw,sync,all_squash)'\'' >/etc/exports' -i 10.0.0.18 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
Fri Sep 22 06:41:40 2023 - ERROR - connection to 10.0.0.18 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Fri Sep 22 06:41:41 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ SSH_CMD 'exportfs -avr' 10.0.0.18 'openEuler12#$' root
+ cmd='exportfs -avr'
+ remoteip=10.0.0.18
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'exportfs -avr' -i 10.0.0.18 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
Fri Sep 22 06:41:46 2023 - ERROR - connection to 10.0.0.18 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Fri Sep 22 06:41:47 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ SSH_CMD 'systemctl restart nfs-server rpcbind' 10.0.0.18 'openEuler12#$' root
+ cmd='systemctl restart nfs-server rpcbind'
+ remoteip=10.0.0.18
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'systemctl restart nfs-server rpcbind' -i 10.0.0.18 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
Fri Sep 22 06:41:52 2023 - ERROR - connection to 10.0.0.18 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Fri Sep 22 06:41:54 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ LOG_INFO 'Environmental preparation is over.'
+ message='Environmental preparation is over.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Environmental preparation is over.'
Fri Sep 22 06:41:55 2023 - INFO  - Environmental preparation is over.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase.'
+ message='Start executing testcase.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase.'
Fri Sep 22 06:41:56 2023 - INFO  - Start executing testcase.
+ SSH_CMD 'sed -i '\''s/^#\\ vers2=n/vers2=n/g'\'' /etc/nfs.conf;sed -i '\''s/^#\\ vers3=y/vers3=n/g'\'' /etc/nfs.conf;
    systemctl restart nfs-server rpcbind' 10.0.0.18 'openEuler12#$' root
+ cmd='sed -i '\''s/^#\\ vers2=n/vers2=n/g'\'' /etc/nfs.conf;sed -i '\''s/^#\\ vers3=y/vers3=n/g'\'' /etc/nfs.conf;
    systemctl restart nfs-server rpcbind'
+ remoteip=10.0.0.18
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'sed -i '\''s/^#\\ vers2=n/vers2=n/g'\'' /etc/nfs.conf;sed -i '\''s/^#\\ vers3=y/vers3=n/g'\'' /etc/nfs.conf;
    systemctl restart nfs-server rpcbind' -i 10.0.0.18 -u root -p 'openEuler12#$' -t 300 -o 22
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
Fri Sep 22 06:42:01 2023 - ERROR - connection to 10.0.0.18 failed.
+ ret=101
+ test 101 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:101'
+ message='Failed in remote CMD operation:101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:101'
Fri Sep 22 06:42:03 2023 - ERROR - Failed in remote CMD operation:101
+ return 101
+ mkdir /home/client
+ systemctl restart nfs-server rpcbind
Job for rpcbind.service failed because the control process exited with error code.
See "systemctl status rpcbind.service" and "journalctl -xeu rpcbind.service" for details.
Job for nfs-server.service canceled.
+ mount -t nfs -o nfsvers=2 10.0.0.18:/home/nfs /home/client
mount.nfs: requested NFS version or transport protocol is not supported
+ CHECK_RESULT 32 32
+ actual_result=32
+ expect_result=32
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 32x
+ return 0
+ mount -t nfs -o nfsvers=3 10.0.0.18:/home/nfs /home/client
Job for rpc-statd.service failed because the control process exited with error code.
See "systemctl status rpc-statd.service" and "journalctl -xeu rpc-statd.service" for details.
mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
+ CHECK_RESULT 32 32
+ actual_result=32
+ expect_result=32
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 32x
+ return 0
+ mount -t nfs -o nfsvers=4 10.0.0.18:/home/nfs /home/client
mount.nfs: No route to host
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_configure_nfsv4.sh line 46'
+ message='oe_test_storage_nfs_configure_nfsv4.sh line 46'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_configure_nfsv4.sh line 46'
Fri Sep 22 06:44:32 2023 - ERROR - oe_test_storage_nfs_configure_nfsv4.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ df -h
+ grep 10.0.0.18
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_configure_nfsv4.sh line 48'
+ message='oe_test_storage_nfs_configure_nfsv4.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_configure_nfsv4.sh line 48'
Fri Sep 22 06:44:33 2023 - ERROR - oe_test_storage_nfs_configure_nfsv4.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of testcase execution.'
+ message='End of testcase execution.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution.'
Fri Sep 22 06:44:35 2023 - INFO  - End of testcase execution.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Sep 22 06:44:36 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Fri Sep 22 06:44:37 2023 - INFO  - start environment cleanup.
+ umount /home/client
umount: /home/client: not mounted.
+ rmdir /home/client
+ SSH_CMD 'rm -rf /home/nfs;yum remove -y nfs-utils;mv -f /etc/exports.bak /etc/exports' 10.0.0.18 'openEuler12#$' root
+ cmd='rm -rf /home/nfs;yum remove -y nfs-utils;mv -f /etc/exports.bak /etc/exports'
+ remoteip=10.0.0.18
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'rm -rf /home/nfs;yum remove -y nfs-utils;mv -f /etc/exports.bak /etc/exports' -i 10.0.0.18 -u root -p 'openEuler12#$' -t 300 -o 22
Fri Sep 22 06:44:39 2023 - WARN  - the remote user uses the default configuration.
Fri Sep 22 06:44:41 2023 - WARN  - the remote password uses the default configuration.
Fri Sep 22 06:44:42 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@10.0.0.18 rm -rf /home/nfs;yum remove -y nfs-utils;mv -f /etc/exports.bak /etc/exports

Authorized users only. All activities may be monitored and reported.
root@10.0.0.18's password: 
Dependencies resolved.
================================================================================
 Package             Architecture Version                  Repository      Size
================================================================================
Removing:
 nfs-utils           riscv64      2:2.6.2-4.oe2309         @mainline      1.3 M
Removing unused dependencies:
 nfs-utils-help      riscv64      2:2.6.2-4.oe2309         @mainline       87 k

Transaction Summary
================================================================================
Remove  2 Packages

Freed space: 1.4 M
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Running scriptlet: nfs-utils-2:2.6.2-4.oe2309.riscv64                     1/1 
  Running scriptlet: nfs-utils-2:2.6.2-4.oe2309.riscv64                     1/2 
Removed "/etc/systemd/system/remote-fs.target.wants/nfs-client.target".
Removed "/etc/systemd/system/multi-user.target.wants/nfs-client.target".
Removed "/etc/systemd/system/multi-user.target.wants/nfs-server.service".

  Erasing          : nfs-utils-2:2.6.2-4.oe2309.riscv64                     1/2 
  Running scriptlet: nfs-utils-2:2.6.2-4.oe2309.riscv64                     1/2 
  Erasing          : nfs-utils-help-2:2.6.2-4.oe2309.riscv64                2/2 
  Running scriptlet: nfs-utils-help-2:2.6.2-4.oe2309.riscv64                2/2 
  Verifying        : nfs-utils-2:2.6.2-4.oe2309.riscv64                     1/2 
  Verifying        : nfs-utils-help-2:2.6.2-4.oe2309.riscv64                2/2 

Removed:
  nfs-utils-2:2.6.2-4.oe2309.riscv64   nfs-utils-help-2:2.6.2-4.oe2309.riscv64  

Complete!
+ ret=0
+ test 0 -ne 0
+ return 0
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Fri Sep 22 06:45:46 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Fri Sep 22 06:45:47 2023 - INFO  - Finish environment cleanup.
